// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CountStats: typeof import('./src/components/CountStats.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Map: typeof import('./src/components/map/Map.vue')['default']
  }
}

export { }
